name: Deploy Pharmacy API

on:
  push:
    branches: [ "main" ]   # Trigger on push to main branch

jobs:
  deploy:
    runs-on: self-hosted   # Your Windows self-hosted runner

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Deploy via PowerShell
      - name: Deploy to Windows Server
        shell: powershell
        run: |
          # Navigate to project folder
          Set-Location "C:\Pharmacy_Assistant"

          # Pull latest code
          git reset --hard
          git clean -fd
          git pull origin main

          # Install/update dependencies
          pip install --upgrade pip
          pip install -r requirements.txt

          # Restart the service using NSSM
          if (Get-Service -Name "PharmacyAssistant" -ErrorAction SilentlyContinue) {
              nssm restart PharmacyAssistant
              Write-Host "PharmacyAssistant service restarted successfully."
          } else {
              Write-Host "Service 'PharmacyAssistant' not found. Please install it first."
          }
