name: Deploy Pharmacy API

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Application
        shell: powershell
        run: |
          # Navigate to project folder
          Set-Location "C:\Pharmacy_Assistant"

          # Copy code from runner to deployment folder
          Remove-Item -Path "C:\Pharmacy_Assistant\*" -Recurse -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE\*" -Destination "C:\Pharmacy_Assistant" -Recurse -Force

          # Install dependencies
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

          # Restart service
          if (Get-Service -Name "PharmacyAssistant" -ErrorAction SilentlyContinue) {
              nssm restart PharmacyAssistant
          } else {
              Write-Host "Service 'PharmacyAssistant' not found. Please install it first."
          }
