name: Deploy Pharmacy API

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Application
        shell: powershell
        run: |
          # Navigate to project folder
          $deployPath = "C:\Users\Admin\Pharmacy_Assistant"
          Set-Location $deployPath

          # Stop the service if it exists
          if (Get-Service -Name "PharmacyAssistant" -ErrorAction SilentlyContinue) {
              Stop-Service -Name "PharmacyAssistant" -Force
              Write-Host "PharmacyAssistant service stopped."
          }

          # Copy/update code from runner workspace to deployment folder
          Copy-Item -Path "$env:GITHUB_WORKSPACE\*" -Destination $deployPath -Recurse -Force
          Write-Host "Code updated successfully."

          # Install dependencies
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          Write-Host "Dependencies installed."

          # Restart the service
          if (Get-Service -Name "PharmacyAssistant" -ErrorAction SilentlyContinue) {
              Start-Service -Name "PharmacyAssistant"
              Write-Host "PharmacyAssistant service restarted successfully."
          } else {
              Write-Host "Service 'PharmacyAssistant' not found. Please install it first."
          }
